[sync_scaffold]

diff_command = "diff -qrs data actual --exclude temp --exclude '*.log' --exclude sync_scaffold.sh"
test_target = "sync_scaffold.sh"

[[sync_scaffold.test_cases]]

name = "Sync scaffold from a commit"
args = "1542c4e0bbc226c28e16d94d78d4b2de6c7fa666"
directory = "test/sync_scaffold/"

[sync_pr]

diff_command = "diff -qrs data actual --exclude temp --exclude '*.log' --exclude sync_pr.sh"
test_target = "sync_pr.sh"

[[sync_pr.test_cases]]

name = "Sync markdown-pages from a TiDB Cloud PR"
args = "preview-cloud/pingcap/docs/10098"
directory = "test/sync_pr_cloud/"

[[sync_pr.test_cases]]

name = "Sync markdown-pages from a docs PR"
args = "preview/pingcap/docs/12929"
directory = "test/sync_pr_docs/"

[[sync_pr.test_cases]]

name = "Sync markdown-pages from a docs-cn PR"
args = "preview/pingcap/docs-cn/14523"
directory = "test/sync_pr_docs_cn/"

[[sync_pr.test_cases]]

name = "Sync markdown-pages from a TiDB Operator PR"
args = "preview-operator/pingcap/docs-tidb-operator/2397"
directory = "test/sync_pr_operator/"

[sync_mult_prs]

diff_command = "diff -qrs data actual --exclude temp --exclude '*.log' --exclude sync_mult_prs.sh --exclude sync_pr.sh"
test_target = "sync_mult_prs.sh"
test_dependencies = ["sync_pr.sh"]

[[sync_mult_prs.test_cases]]

name = "Sync markdown-pages from multiple PRs"
args = ""
directory = "test/sync_mult_prs/"
