name: Sync a PR

on:
  push:
    branches:
      - preview/**
      - preview-cloud/**
      - preview-operator/**
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  sync_pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout current repo
      uses: actions/checkout@v3

    - name: Run sync_pr script
      run: |
        git config user.name "Docsite Preview Bot"
        git config user.email ""
        ./sync_pr.sh
        ./.github/git_push.sh ${{ github.ref_name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
